elearning:
    resource: "@ElearningBundle/Controller"
    type: annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
create_lesson:
    pattern: /categories/{categoryId}/lesson/new
    defaults: {_controller: ElearningBundle:Lesson:create}