ElearningBundle\Entity\Result:
    type: entity
    repositoryClass: ElearningBundle\Repository\ResultRepository
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    lifecycleCallbacks: {  }
    manyToOne:
        lesson:
            targetEntity: Lesson
            inversedBy: results
            joinColumn:
                name: lesson
                referencedColumnName: id
        answer:
            targetEntity: Answer
            inversedBy: results
            joinColumn:
                name: answer
                referencedColumnName: id
        word:
            targetEntity: Word
            inversedBy: results
            joinColumn:
                name: word
                referencedColumnName: id
