ElearningBundle\Entity\User:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
            notnull: true
        email:
            type: string
            length: 255
            notnull: true
        password:
            type: string
            length: 255
            notnull: true
        salt:
            type: string
            length: 255
        active:
            type: boolean
            notnull: true
        created_at:
            type: date
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    lifecycleCallbacks: {  }
    oneToMany:
        lessons:
            targetEntity: Lesson
            mappedBy: User
